# Generated by Django 5.2.4 on 2025-09-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('proyecto', models.CharField(max_length=200)),
                ('espacio', models.CharField(max_length=200)),
                ('prioridad', models.CharField(default='media', max_length=10)),
                ('fechaInicio', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('tareaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtareas', to='tasks.tasks')),
            ],
        ),
    ]
